M48
; DRILL file {KiCad 7.0.8} date Fri Dec  1 02:06:56 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-01T02:06:56-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X7.0179Y-1.7803
X7.0179Y-3.6287
X7.9829Y-1.7803
X7.9829Y-3.6287
T0
M30
